apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: public-ord1
    metallb.universe.tf/allow-shared-ip: default
  name: generator-a40
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: generator-a40
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: generator-a40