apiVersion: apps/v1
kind: Deployment
metadata:
  name: generator-a100
  labels:
    app: generator-a100
spec:
  replicas: 1
  selector:
    matchLabels:
      app: generator-a100
  template:
    metadata:
      name: generator-a100-nvlink
      labels:
        app: generator-a100-nvlink
    spec:
      containers:
        - name: generator
          image: ghcr.io/brianlechthaler/llama-k8s/generator:main
          imagePullPolicy: Always
          env:
            - name: APP_PORT
              value: "8080"
            - name: EXEC_PORT
              value: "8080"
            - name: BUCKET_REGION
              value: "las1"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-full-secret
                  key: accessKey
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-full-secret
                  key: secretKey
            - name: FILE_NAME
              value: "ggml-model-f16.gguf"
          resources:
            limits:
              cpu: 32
              memory: 64Gi
              nvidia.com/gpu: 2
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/region
                    operator: In
                    values:
                      - LAS1
                  - key: gpu.nvidia.com/class
                    operator: In
                    values:
                      - A100_NVLINK_80GB
      restartPolicy: Always