apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: generator
spec:
  template:
    spec:
      containers:
      - image: ghcr.io/brianlechthaler/llama-k8s/generator:main
        imagePullPolicy: Always
        volumeMounts:
          - name: model-storage
            mountPath: /opt/model
        env:
          - name: APP_PORT
            value: "8080"
          - name: EXEC_PORT
            value: "8080"
        resources:
          limits:
            cpu: 8
            memory: 16Gi
            nvidia.com/gpu: 3
      volumes:
        - name: model-storage
          persistentVolumeClaim:
            claimName: model-storage-claim
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/region
                    operator: In
                    values:
                      - ORD1
                  - key: gpu.nvidia.com/class
                    operator: In
                    values:
                      - A40