apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-storage-claim
spec:
  storageClassName: block-nvme-ord1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti