apiVersion: batch/v1
kind: Job
metadata:
  name: model-download
spec:
  template:
    spec:
      containers:
      - name: model-downloader
        image: ghcr.io/brianlechthaler/llama-k8s/model_downloader:main
        imagePullPolicy: Always
        volumeMounts:
          - name: model-storage
            mountPath: /opt/model
          - name: model-cache
            mountPath: /opt/model_cache
        resources:
          limits:
            cpu: 8
            memory: 16Gi
        env:
          - name: HF_TOKEN
            valueFrom:
              secretKeyRef:
                name: hf-token-secret
                key: hf_token
      volumes:
        - name: model-storage
          persistentVolumeClaim:
            claimName: model-storage-claim
        - name: model-cache
          persistentVolumeClaim:
            claimName: model-cache-claim
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/region
                operator: In
                values:
                  - LAS1
      restartPolicy: OnFailure
  backoffLimit: 10