apiVersion: batch/v1
kind: Job
metadata:
  name: create-bucket
spec:
  template:
    spec:
      containers:
      - name: create-bucket
        image: ghcr.io/brianlechthaler/llama-k8s/uploader:main
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 4
            memory: 8Gi
        env:
          - name: BUCKET_NAME
            valueFrom:
              secretKeyRef:
                name: s3-bucket
                key: name
          - name: BUCKET_REGION
            value: "las1"
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: s3-full-secret
                key: accessKey
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: s3-full-secret
                key: secretKey
          - name: OPERATION
            value: "create_bucket"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/region
                operator: In
                values:
                  - LAS1
      restartPolicy: OnFailure
  backoffLimit: 10